
services:
  backend:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: coverletterai
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d