
volumes:
  db-data:

services:
  proxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  backend:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - db-data:/app/data
    restart: always
  db:
    image: mysql
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: coverletterai
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db-data:/app/data

    restart: always

networks:
  default:
    external:
      name: nginxproxymanager_default