name: CI

on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout project
      uses: actions/checkout@v2
    - name: Deploy project
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{secrets.SSH_HOST}}
        username: ${{secrets.USER}}
        password: ${{secrets.PASSWORD}}
        port: ${{secrets.PORT}}
        command_timeout: 200m
        script: |
          echo "ssh connection successful !"
          docker compose stop
          rm -r ./coverletterai-backend
          git clone "git@github.com:elpolloloco6498/coverletterai-backend.git"
          cd ./coverletterai-backend
          docker compose up --force-recreate --build -d
          docker image prune -f
